### ISSUE TITLE
Broken Portal

### ISSUE THREAD

**Issue by Soltect** [open-automation/switch-portals#24] opened 2018-10-16 22:17 UTC
Hi,

Just a quick introduction: I'm Enfocus Switch Partner in Australia and I'm experiencing with some of my customers that the link of the In or Out Portal get broken.
I have attached a screenshot and temp folder 524.

Can you investigate and come back to me as it is a rondo issue and very hard to track too.

Thanks in Advance,
Yves
![screen shot 2018-10-16 at 08 39 45](https://user-images.githubusercontent.com/44214592/47050762-4a5f1600-d1ed-11e8-956d-16d5df8726ce.png)
[524.zip](https://github.com/open-automation/switch-portals/files/2485127/524.zip)

**Comment by Dominick-Peluso-Bose** [comment] 2018-12-12 04:06
Hi @Soltect, sorry I did not respond sooner. This appears to be a duplicate of #21

**Closed as completed** 2018-12-12 04:07 UTC
Labels: duplicate
